sudo: required
dist: trusty

language: python

python:
  - "3.4"

cache:
  apt: true

addons:
  apt:
    packages:
      - cmake
      - libcppunit-dev

install:
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -P symbsat-cpp/tests
  - pip install -U pip setuptools
  - pip install coverage

script:
  - (cd symbsat-py && coverage run --branch -m unittest tests/test_*.py)
  - (mkdir build && cd build && cmake ../symbsat-cpp && make -j2 && tests/unittests)

after_success:
  - (cd symbsat-cpp && bash <(curl -s https://codecov.io/bash))
