sudo: required
dist: trusty

language: python

python:
  - "3.4"

cache:
  apt: true

addons:
  apt:
    packages:
      - cmake
      - libcppunit-dev

install:
  - pip install -U pip setuptools
  - pip install coverage

script:
  - (cd symbsat-py && coverage run -m unittest tests/test_*.py)
  - "(
      mkdir build &&
      cd build &&
      cmake ../symbsat-cpp &&
      make &&
      tests/unittest
  )"

after_success:
    - "(cd symbsat-py && bash <(curl -s https://codecov.io/bash))"
